name = "SpgLib"
uuid = "e77a6fe8-bb58-11e9-2584-436ec1627d69"
authors = ["Qi Zhang <singularitti@outlook.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
